"""A single self-contained HTML page an examiner can open and be convinced by."""
from __future__ import annotations

import html
import os
from pathlib import Path

from core.geometry import NormalizedRect, format_timestamp
from core.models import Calibration, ClosestApproach, VideoMeta

CSS = """
:root{--bg:#0f1115;--card:#171a21;--line:#252a34;--fg:#e8ecf3;--mut:#9aa5b5;
      --acc:#4da3ff;--warn:#ffb347;--bad:#ff6b6b;--good:#5ddb9a}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);
     font:15px/1.6 -apple-system,Segoe UI,Roboto,sans-serif}
.wrap{max-width:1180px;margin:0 auto;padding:32px 20px 80px}
h1{font-size:30px;margin:0 0 6px} h2{font-size:20px;margin:38px 0 12px;
   border-bottom:1px solid var(--line);padding-bottom:8px}
h3{font-size:16px;margin:22px 0 8px}
.sub{color:var(--mut);margin:0 0 24px}
.grid{display:grid;gap:14px;grid-template-columns:repeat(auto-fit,minmax(190px,1fr))}
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px}
.kpi{font-size:26px;font-weight:650;color:var(--acc)}
.kpi.good{color:var(--good)} .kpi.warn{color:var(--warn)}
.lbl{color:var(--mut);font-size:12.5px;text-transform:uppercase;letter-spacing:.04em}
img{max-width:100%;border-radius:10px;display:block;border:1px solid var(--line)}
video{max-width:100%;border-radius:10px;border:1px solid var(--line)}
table{border-collapse:collapse;width:100%;font-size:13px}
th,td{padding:7px 9px;border-bottom:1px solid var(--line);text-align:right;
      white-space:nowrap}
th{color:var(--mut);font-weight:600;text-align:right;position:sticky;top:0;
   background:var(--card)}
th:first-child,td:first-child{text-align:left}
.scroll{overflow-x:auto;background:var(--card);border:1px solid var(--line);
        border-radius:12px;padding:6px 12px;max-height:560px;overflow-y:auto}
.veh{background:var(--card);border:1px solid var(--line);border-radius:12px;
     padding:18px;margin:16px 0}
.two{display:grid;gap:16px;grid-template-columns:1fr 1fr}
@media(max-width:860px){.two{grid-template-columns:1fr}}
code{background:#0b0d11;padding:2px 6px;border-radius:5px;color:var(--acc)}
.note{background:#151a24;border-left:3px solid var(--acc);padding:12px 16px;
      border-radius:0 8px 8px 0;margin:14px 0;color:#c8d3e2}
.ok{color:var(--good)} .bad{color:var(--bad)} .mut{color:var(--mut)}
"""


EMERGENCY_MARK = " &#9888;"


def _rel(path: str | Path | None, base: Path) -> str:
    if not path:
        return ""
    try:
        return os.path.relpath(str(path), str(base)).replace("\\", "/")
    except ValueError:
        return str(path)


class ReportService:
    def __init__(self, out_dir: Path):
        self.out_dir = out_dir

    def build(
        self,
        job_id: int,
        meta: VideoMeta,
        calib: Calibration,
        rect: NormalizedRect,
        approaches: list[ClosestApproach],
        validation: dict,
        artifacts: dict,
        media: dict[int, dict[str, str]],
    ) -> Path:
        v = validation
        spread = v.get("cross_metric_spread_frames", {})
        depth = v.get("cross_metric_depth_spread", {})
        naive = v.get("naive_area_baseline_error_frames", {})

        parts: list[str] = [
            "<!-- generated by report_service -->",
            f"<style>{CSS}</style>",
            '<div class="wrap">',
            f"<h1>Closest-approach report &mdash; job {job_id}</h1>",
            f'<p class="sub">{html.escape(Path(meta.path).name)} &middot; '
            f"{meta.width}&times;{meta.height} &middot; {meta.fps:.2f} fps &middot; "
            f"{meta.frame_count} frames &middot; {meta.duration:.1f} s</p>",
        ]

        # ------------------------------------------------------------ KPIs
        parts.append('<div class="grid">')
        parts.append(self._kpi("vehicles captured", v.get("vehicles", 0)))
        parts.append(self._kpi("triggered by the zone", v.get("vehicles_triggered_by_zone", 0)))
        parts.append(self._kpi(
            "3-metric agreement &le;1 frame",
            f"{spread.get('within_1_frame_pct', 0)}%", "good"))
        parts.append(self._kpi(
            "3-metric depth spread (median)",
            f"{depth.get('median_pct', 0):.2f}%", "good"))
        parts.append(self._kpi(
            "naive argmax(area) disagrees on",
            f"{naive.get('disagreed_pct') or 0}%", "warn"))
        parts.append(self._kpi("timing resolution", f"{v.get('timing_precision_seconds', 0):.3f} s"))
        parts.append("</div>")

        by_type = v.get("vehicles_by_type", {})
        if by_type:
            parts.append('<div class="grid" style="margin-top:14px">')
            for kind, count in sorted(by_type.items(), key=lambda kv: -kv[1]):
                tone = "warn" if kind == "emergency" else ""
                parts.append(self._kpi(html.escape(kind), count, tone))
            parts.append("</div>")

        parts.append(
            '<div class="note"><b>How to read this.</b> The system fixes a virtual '
            "rectangle on the road nearest the camera. A vehicle arms the capture when its "
            "road-contact point enters that rectangle; the exact frame is then chosen inside "
            "the dwell window by three <i>independent</i> geometric depth estimates. "
            "Agreement between those three, and the size of the error the naive "
            "<code>argmax(area)</code> baseline would have made, are the numbers to check.</div>"
        )

        # --------------------------------------------------- configuration
        parts += [
            "<h2>1 &middot; Capture zone &amp; recovered geometry</h2>",
            '<div class="two">',
            '<div class="card">',
            "<h3>Virtual rectangle (normalised)</h3>",
            f"<p><code>x={rect.x:.3f}  y={rect.y:.3f}  w={rect.w:.3f}  h={rect.h:.3f}</code><br>"
            f'<span class="mut">= pixels ({rect.x * meta.width:.0f}, {rect.y * meta.height:.0f}) '
            f"to ({(rect.x + rect.w) * meta.width:.0f}, "
            f"{(rect.y + rect.h) * meta.height:.0f})</span></p>",
            "<h3>Camera, recovered from the detections</h3>",
            "<table>"
            f"<tr><td>horizon row</td><td>{calib.horizon_y:.1f} px</td></tr>"
            f"<tr><td>fit R&sup2;</td><td>{calib.r_squared:.4f}</td></tr>"
            f"<tr><td>camera height</td><td>{calib.camera_height_m:.2f} m</td></tr>"
            f"<tr><td>focal length</td><td>{calib.focal_px:.0f} px</td></tr>"
            f"<tr><td>samples in fit</td><td>{calib.n_samples}</td></tr>"
            "</table>",
            "</div>",
            f'<div class="card"><img src="{_rel(artifacts.get("calibration_plot"), self.out_dir)}"></div>',
            "</div>",
        ]

        # ---------------------------------------------------- validation
        parts += [
            "<h2>2 &middot; Numeric validation</h2>",
            f'<img src="{_rel(artifacts.get("agreement_plot"), self.out_dir)}">',
            '<div class="grid" style="margin-top:14px">',
            self._kpi("&le;1 frame", f"{spread.get('within_1_frame_pct', 0)}%", "good"),
            self._kpi("&le;3 frames", f"{spread.get('within_3_frames_pct', 0)}%", "good"),
            self._kpi("p90 spread", f"{spread.get('p90', 0):.0f} fr"),
            self._kpi("depth spread &le;1%", f"{depth.get('within_1_pct', 0)}%", "good"),
            self._kpi("p90 depth spread", f"{depth.get('p90_pct', 0):.2f}%"),
            self._kpi("naive baseline wrong on", f"{naive.get('disagreed_pct') or 0}%", "warn"),
            self._kpi("naive worst error", f"{naive.get('max') or 0:.0f} fr", "warn"),
            "</div>",
            '<div class="note">Three depth estimates built from different parts of the '
            "bounding box &mdash; the road-contact point, the apparent width, and the box area "
            "&mdash; are computed separately and only compared afterwards. They share no "
            "intermediate quantity except the calibration, so their converging on the same "
            "frame is evidence the frame is right. The naive baseline column shows the error "
            "made by the obvious approach, which is fooled by the box being cropped at the "
            "image border precisely when the vehicle is nearest.<br><br>"
            "<b>Frames or metres?</b> A frame count alone misreads congested footage: a "
            "vehicle crawling in a queue sits at nearly the same distance for a second at a "
            "time, so the three estimates land on frames far apart while agreeing on the "
            "distance to within noise. The depth-spread column measures how much the "
            "disagreement actually costs, and is the number to trust when traffic is "
            "slow.</div>",
            "<h3>Timeline</h3>",
            f'<img src="{_rel(artifacts.get("timeline_plot"), self.out_dir)}">',
        ]

        # ------------------------------------------------------ the video
        annotated = artifacts.get("annotated_video")
        if annotated:
            parts += [
                "<h2>3 &middot; Annotated video</h2>",
                f'<video controls src="{_rel(annotated, self.out_dir)}"></video>',
                '<p class="mut">Yellow rectangle = capture zone. Blue box = tracked. '
                "Yellow box = inside the zone (armed). Red flash + label = the captured "
                "closest-approach frame for that vehicle.</p>",
            ]

        # ------------------------------------------------------- results
        parts += [
            "<h2>4 &middot; Results table</h2>",
            '<div class="scroll">',
            self._table(approaches),
            "</div>",
            f'<p class="mut">Also written as '
            f'<code>{_rel(artifacts.get("results_csv"), self.out_dir)}</code> and '
            f'<code>{_rel(artifacts.get("results_json"), self.out_dir)}</code>.</p>',
        ]

        # ------------------------------------------------- per vehicle
        parts.append("<h2>5 &middot; Per-vehicle evidence</h2>")
        for a in approaches:
            m = media.get(a.track_id, {})
            parts += [
                '<div class="veh">',
                f"<h3>#{a.track_id} &middot; {html.escape(a.vehicle_type)} &middot; "
                f"frame {a.frame_index} &middot; t = {format_timestamp(a.refined_timestamp)} "
                f"&middot; {a.distance_m:.1f} m "
                f'<span class="mut">&middot; box ['
                f"{a.box[0]:.0f}, {a.box[1]:.0f}, {a.box[2]:.0f}, {a.box[3]:.0f}]</span></h3>",
                f'<img src="{_rel(m.get("contact_sheet_path"), self.out_dir)}">',
                '<div class="two" style="margin-top:14px">',
                f'<img src="{_rel(m.get("plot_path"), self.out_dir)}">',
                f'<img src="{_rel(m.get("snapshot_path"), self.out_dir)}">',
                "</div>",
                "</div>",
            ]

        parts.append("</div>")
        path = self.out_dir / "report.html"
        path.write_text("\n".join(parts), encoding="utf-8")
        return path

    # ------------------------------------------------------------- helpers
    @staticmethod
    def _kpi(label: str, value, tone: str = "") -> str:
        return (f'<div class="card"><div class="lbl">{label}</div>'
                f'<div class="kpi {tone}">{value}</div></div>')

    @staticmethod
    def _table(approaches: list[ClosestApproach]) -> str:
        head = ("track", "type", "frame", "timestamp", "dist m", "bbox",
                "ground", "width", "area", "spread", "Δdepth", "naive", "naive Δ", "zone")
        rows = ["<tr>" + "".join(f"<th>{h}</th>" for h in head) + "</tr>"]
        for a in approaches:
            picks = {p.name: p.frame_index for p in a.picks}
            delta = (a.naive_area_frame - a.frame_index) if a.naive_area_frame is not None else 0
            cls = "bad" if abs(delta) > 2 else "mut"
            rows.append(
                "<tr>"
                f"<td>#{a.track_id}</td><td>{html.escape(a.vehicle_type)}"
                f"{EMERGENCY_MARK if a.is_emergency else str()}</td>"
                f"<td>{a.frame_index}</td>"
                f"<td>{format_timestamp(a.refined_timestamp)}</td>"
                f"<td>{a.distance_m:.1f}</td>"
                f"<td>{a.box[0]:.0f},{a.box[1]:.0f},{a.box[2]:.0f},{a.box[3]:.0f}</td>"
                f"<td>{picks.get('ground', '-')}</td>"
                f"<td>{picks.get('width', '-')}</td>"
                f"<td>{picks.get('diag', '-')}</td>"
                f"<td>{a.agreement_frames}</td>"
                f"<td>{a.agreement_distance_pct:.2f}%</td>"
                f"<td>{a.naive_area_frame}</td>"
                f'<td class="{cls}">{delta:+d}</td>'
                f"<td>{'yes' if a.entered_zone else 'no'}</td>"
                "</tr>"
            )
        return "<table>" + "".join(rows) + "</table>"
